# -*- coding: utf-8 -*-
"""
Created on Fri Sep 11 08:45:13 2020
@author: halle

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

def fib(limit):
    lst=[1]
    result = 2
    while result < limit:
        lst.append(result)
        result = lst[-2]+lst[-1]
    lst_even = [lst[i] for i in range(len(lst)) if lst[i] % 2 ==0]
    return lst_even


print(sum(fib(4000000)))

# 4613732